require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/**/*

# METRICS RULES
Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 200


Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 200

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 60
  Exclude:
    - db/migrate/**/*
    - db/seeds.rb

# BUNDLER RULES
Bundler/OrderedGems:
  Enabled: false

# STYLE RULES
Style/WordArray:
  MinSize: 5

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false


Style/BlockComments:
  Enabled: false

# Forces Ruby 2.6 style of endless ranges: [0..] instead of [0..-1]
Style/SlicingWithRange:
  Enabled: false

# Forces to remove backslash escapes that are automatically identified by ruby
# Example match(/[\,\.]/) => match(/[,.]/)
# It's more readable, but harder to test with regex validators that can't do this magic.
Style/RedundantRegexpEscape:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

# LAYOUT RULES
Layout/LineLength:
  Max: 120
  Exclude:
    - db/migrate/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/EmptyClass:
  Enabled: false

# RAILS RULES
Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - lib/tasks/**/*
    - db/seeds.rb

Rails/FilePath:
  EnforcedStyle: arguments

Rails/SkipsModelValidations:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: true
  Exclude:
    - 'db/migrate/**/*'
