default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prompt_search_development
  host: localhost
  username: postgres
  password: password

test:
  <<: *default
  database: cgtrader_search_test

production:
  <<: *default
  database: cgtrader_search_production
  username: cgtrader_search
  password: <%= ENV["CGTRADER_SEARCH_DATABASE_PASSWORD"] %>
